build:snap:
  stage: build
  image: kenvandine/gnome-3-26-1604
  script: 
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - export SNAP_ARCH=amd64
    - echo $LOGIN | snapcraft login --with -
    - SNAPCRAFT_SETUP_CORE=1 snapcraft
    - snapcraft push gtk-common-themes*.snap
    - snapcraft logout
  allow_failure: false
  artifacts:
    paths: ['./*.snap']
    expire_in: 3 days
