build:snap:
  stage: build
  image: ubuntudesktop/gnome-3-26-1604
  script: 
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - export SNAP_ARCH=amd64
    - add-apt-repository -y ppa:ken-vandine/gnome-3-26
    - apt-get -y update
    - apt-get -y upgrade
    - echo $LOGIN | snapcraft login --with -
    - SNAPCRAFT_SETUP_CORE=1 snapcraft
    - |
       if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
         snapcraft push gtk-common-themes*.snap --release edge
       fi
    - snapcraft logout
  allow_failure: false
  artifacts:
    paths: ['./*.snap']
    expire_in: 3 days
