# Variables used by the build job.  These are usually overriden by the
# project or trigger request.
variables:
  LOGIN: ""
  RELEASE_CHANNEL: "edge"
  YARU_SOURCE_COMMIT: ""

build:snap:
  stage: build
  image: ubuntudesktop/gnome-3-28-1804
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - export SNAP_ARCH=amd64
    - export SNAPCRAFT_BUILD_INFO=1
    - apt-get update
    - apt-get install -y git
    - |
      if [ -n "$YARU_SOURCE_COMMIT" ]; then
        # Ideally we'd just pass the the revision ID to snapcraft as
        # source-commit.  However, that seems to fail for revisions
        # not in master:
        #   https://bugs.launchpad.net/snapcraft/+bug/1817970
        # Instead clone the repo ourselves and point at the local copy.
        git clone https://github.com/ubuntu/yaru.git yaru
        git -C yaru fetch origin "+${YARU_SOURCE_COMMIT}:"
        git -C yaru reset --hard "${YARU_SOURCE_COMMIT}"
        sed -i "s|https://github.com/ubuntu/yaru.git|./yaru|" snap/snapcraft.yaml
      fi
    - SNAPCRAFT_SETUP_CORE=1 snapcraft
    - |
       if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
         echo "$LOGIN" | snapcraft login --with -
         snapcraft push gtk-common-themes*.snap --release "$RELEASE_CHANNEL"
         snapcraft logout
       fi
  allow_failure: false
  artifacts:
    paths: ['./*.snap']
    expire_in: 7 days
