name: gtk-common-themes
version: '0.1'
architectures:
  - all
summary: All the (common) themes
description: |
  A snap that exports the GTK and icon themes used on various Linux distros.

grade: stable
confinement: strict

slots:
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Adwaita
        - $SNAP/share/themes/Adwaita-dark
        - $SNAP/share/themes/HighContrast
        - $SNAP/share/themes/Ambiance
        - $SNAP/share/themes/Radiance
        - $SNAP/share/themes/Arc
        - $SNAP/share/themes/Arc-Dark
        - $SNAP/share/themes/Arc-Darker
        - $SNAP/share/themes/Communitheme
        - $SNAP/share/themes/Yaru
        - $SNAP/share/themes/elementary
        - $SNAP/share/themes/Mint-X
        - $SNAP/share/themes/Mint-Y
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Adwaita
        - $SNAP/share/icons/hicolor
        - $SNAP/share/icons/HighContrast
        - $SNAP/share/icons/Humanity
        - $SNAP/share/icons/Humanity-Dark
        - $SNAP/share/icons/ubuntu-mono-dark
        - $SNAP/share/icons/ubuntu-mono-light
        - $SNAP/share/icons/DMZ-Black
        - $SNAP/share/icons/DMZ-White
        - $SNAP/share/icons/communitheme
        - $SNAP/share/icons/Suru
        - $SNAP/share/icons/Yaru
        - $SNAP/share/icons/elementary
        - $SNAP/share/icons/Mint-X
        - $SNAP/share/icons/Mint-X-Aqua
        - $SNAP/share/icons/Mint-X-Blue
        - $SNAP/share/icons/Mint-X-Brown
        - $SNAP/share/icons/Mint-X-Dark
        - $SNAP/share/icons/Mint-X-Grey
        - $SNAP/share/icons/Mint-X-Orange
        - $SNAP/share/icons/Mint-X-Pink
        - $SNAP/share/icons/Mint-X-Purple
        - $SNAP/share/icons/Mint-X-Red
        - $SNAP/share/icons/Mint-X-Sand
        - $SNAP/share/icons/Mint-X-Teal
        - $SNAP/share/icons/Mint-X-Yellow
        - $SNAP/share/icons/Mint-Y
        - $SNAP/share/icons/Mint-Y-Aqua
        - $SNAP/share/icons/Mint-Y-Blue
        - $SNAP/share/icons/Mint-Y-Brown
        - $SNAP/share/icons/Mint-Y-Grey
        - $SNAP/share/icons/Mint-Y-Orange
        - $SNAP/share/icons/Mint-Y-Pink
        - $SNAP/share/icons/Mint-Y-Purple
        - $SNAP/share/icons/Mint-Y-Red
        - $SNAP/share/icons/Mint-Y-Sand
  sound-themes:
    interface: content
    source:
      read:
        - $SNAP/share/sounds/communitheme
        - $SNAP/share/sounds/Yaru

parts:
  # The base icon theme
  hicolor-icon-theme:
    plugin: autotools
    source: git://anongit.freedesktop.org/xdg/default-icon-theme
    source-type: git
    override-build: &update-icon-cache |
      set -ex
      snapcraftctl build
      for dir in $SNAPCRAFT_PART_INSTALL/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache -q $dir
        fi
      done

    build-packages:
      - gtk-update-icon-cache
      - gnome-common

  # GNOME's default icon theme, also used by Fedora
  adwaita-icon-theme:
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/adwaita-icon-theme.git
    source-type: git
    override-build: *update-icon-cache
    stage:
      - -share/pkgconfig

    build-packages:
      - gtk-update-icon-cache

  # GNOME's default GTK theme, and Accessibility GTK/icon themes
  gnome-themes-extra:
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/gnome-themes-extra.git
    source-type: git
    configflags:
      - --disable-gtk2-engine
    override-build: *update-icon-cache

    stage:
      - -share/locale
      - -share/themes/*/gtk-2.0

    build-packages:
      - gtk-update-icon-cache
      - libgtk-3-dev
      - librsvg2-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - gnome-common

  # Ubuntu's default GTK and icon themes
  ubuntu-themes:
    plugin: nil
    stage-packages:
      - light-themes
      - humanity-icon-theme
      - ubuntu-mono
      - dmz-cursor-theme
    override-build: |
      set -ex
      snapcraftctl build
      for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache -q $dir
        fi
      done

    build-packages:
      - gtk-update-icon-cache
    organize:
      usr/share/icons: share/icons
      usr/share/themes: share/themes
    stage:
      - share/icons/Humanity
      - share/icons/Humanity-Dark
      - share/icons/ubuntu-mono-dark
      - share/icons/ubuntu-mono-light
      - share/icons/DMZ-Black
      - share/icons/DMZ-White
      - share/themes/*/gtk-3*

  # Elementary gtk theme
  elementary-gtk-theme:
    plugin: meson
    source: https://github.com/elementary/stylesheet.git
    source-type: git
    organize:
      usr/share/themes: share/themes
    meson-parameters: [--prefix=/usr]
    stage:
      - share/themes/*/gtk-3*
      - share/themes/*/assets
    build-packages:
      - libgtk-3-dev
      - libglib2.0-dev
      - gnome-common

  # Elementary icon theme
  elementary-icon-theme:
    plugin: meson
    source: https://github.com/elementary/icons.git
    source-type: git
    # Set scale_factors to 1, it does some funky linking
    meson-parameters: [--prefix=/usr, -Dscale_factors=1, -Dvolume_icons=false]
    organize:
      usr/share/icons: share/icons
    override-build: |
      set -ex
      # Don't include cursors, it does some funky linking
      sed -i.bak -e "s|subdir('cursors')||g" meson.build
      snapcraftctl build
      gtk-update-icon-cache -q $SNAPCRAFT_PART_INSTALL/usr/share/icons/elementary
    stage:
      - share/icons/elementary
    build-packages:
      - gtk-update-icon-cache
    
  # Mint-X is the default icon theme in Linux Mint 18
  mint-x-icons:
    source: https://github.com/linuxmint/mint-x-icons.git
    plugin: nil
    override-build: |
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      cp -a usr/share/icons/* $SNAPCRAFT_PART_INSTALL/share/icons/
      find $SNAPCRAFT_PART_INSTALL/share/icons -name apps |xargs rm -rf
      find $SNAPCRAFT_PART_INSTALL/share/icons -name panel |xargs rm -rf

  # Mint-Y is the default icon theme in Linux Mint 19
  mint-y-icons:
    source: https://github.com/linuxmint/mint-y-icons.git
    plugin: nil
    override-build: |
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      cp -a usr/share/icons/* $SNAPCRAFT_PART_INSTALL/share/icons/
      find $SNAPCRAFT_PART_INSTALL/share/icons -name apps |xargs rm -rf
      find $SNAPCRAFT_PART_INSTALL/share/icons -name panel |xargs rm -rf

  # Arc: common third party theme
  arc-theme:
    plugin: autotools
    source: https://github.com/horst3180/arc-theme.git
    source-type: git
    configflags:
      - --disable-cinnamon
      - --disable-gnome-shell
      - --disable-gtk2
      - --disable-metacity
      - --disable-unity
      - --disable-xfwm

  # Communitheme: we want the communitheme and this one to be in sync for bug reports
  # as it's a fast evolving WIP theme.
  # Download from select channel the corresponding snap (can be from a branch channel)
  # and copy its relevant content to this snap
  # It's currently only available on amd64 as built by Travis.
  communitheme:
    plugin: nil
    build-packages: [snapd]
    # note: build-snaps causes a segfault in docker
    override-pull: |
      set -eu
      snap download communitheme --edge
      unsquashfs communitheme*.snap
    override-build: |
      set -eu
      cp -a squashfs-root/share $SNAPCRAFT_PART_INSTALL/
      rm -rf $SNAPCRAFT_PART_INSTALL/share/gnome-shell/

  # Mint is the default theme in Linux Mint
  mint-themes:
    source: https://github.com/linuxmint/mint-themes.git
    plugin: make
    build-packages:
      - ruby-sass
    override-build: |
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
      cp -a src/Mint-*/theme/* $SNAPCRAFT_PART_INSTALL/share/themes/

  # Yaru, the new official Ubuntu theme in 18.10 (formerly known by its code name Communitheme)
  yaru:
    after: [ sassc ]
    source: https://github.com/ubuntu/yaru.git
    plugin: meson
    meson-parameters: [ --prefix=/ ]
    override-build: |
      snapcraftctl build
      # remove unused artefacts in the snap (sessions and schemas)
      rm -rf $SNAPCRAFT_PART_INSTALL/share/*sessions $SNAPCRAFT_PART_INSTALL/share/glib-2.0
      # don't support dark variant until it's ready
      rm -r $SNAPCRAFT_PART_INSTALL/share/themes/*-dark
  sassc:
    after: [ libsass ]
    source: https://github.com/sass/sassc.git
    source-tag: 3.5.0
    plugin: autotools
    override-prime: ""
  libsass:
    source: https://github.com/sass/libsass.git
    source-tag: 3.5.0
    plugin: autotools
    override-prime: ""
