name: gtk-common-themes
version: '0.1'
architectures:
  - all
summary: All the (common) themes
description: |
  A snap that exports the GTK and icon themes used on various Linux distros.

grade: stable
confinement: strict

slots:
  gtk3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Adwaita
        - $SNAP/share/themes/Adwaita-dark
        - $SNAP/share/themes/HighContrast
        - $SNAP/share/themes/Ambiance
        - $SNAP/share/themes/Radiance
        - $SNAP/share/themes/EvoPop
        - $SNAP/share/themes/EvoPop-Azure
        - $SNAP/share/themes/Arc
        - $SNAP/share/themes/Arc-Dark
        - $SNAP/share/themes/Arc-Darker
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Adwaita
        - $SNAP/share/icons/hicolor
        - $SNAP/share/icons/HighContrast
        - $SNAP/share/icons/Humanity
        - $SNAP/share/icons/Humanity-Dark
        - $SNAP/share/icons/ubuntu-mono-dark
        - $SNAP/share/icons/ubuntu-mono-light
        - $SNAP/share/icons/DMZ-Black
        - $SNAP/share/icons/DMZ-White

parts:
  # The base icon theme
  hicolor-icon-theme:
    plugin: autotools
    source: git://anongit.freedesktop.org/xdg/default-icon-theme
    install: &update-icon-cache |
      set -ex
      for dir in $SNAPCRAFT_PART_INSTALL/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache -q $dir
        fi
      done

    build-packages:
      - gtk-update-icon-cache

  # GNOME's default icon theme, also used by Fedora
  adwaita-icon-theme:
    plugin: autotools
    source: git://git.gnome.org/adwaita-icon-theme
    install: *update-icon-cache

    stage:
      - -share/pkgconfig

    build-packages:
      - gtk-update-icon-cache

  # GNOME's default GTK theme, and Accessibility GTK/icon themes
  gnome-themes-extra:
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/gnome-themes-extra.git
    configflags:
      - --disable-gtk2-engine
    install: *update-icon-cache

    stage:
      - -share/locale
      - -share/themes/*/gtk-2.0

    build-packages:
      - gtk-update-icon-cache
      - libgtk-3-dev
      - librsvg2-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev

  # Ubuntu's default GTK and icon themes
  ubuntu-themes:
    plugin: nil
    stage-packages:
      - light-themes
      - humanity-icon-theme
      - ubuntu-mono
      - dmz-cursor-theme
    install: |
      set -ex
      for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache -q $dir
        fi
      done

    build-packages:
      - gtk-update-icon-cache
    organize:
      usr/share/icons: share/icons
      usr/share/themes: share/themes
    stage:
      - share/icons/Humanity
      - share/icons/Humanity-Dark
      - share/icons/ubuntu-mono-dark
      - share/icons/ubuntu-mono-light
      - share/icons/DMZ-Black
      - share/icons/DMZ-White
      - share/themes/*/gtk-3*

  # Solus's default GTK theme
  evopop-gtk-theme:
    source: https://github.com/solus-project/evopop-gtk-theme.git
    source-type: git
    plugin: dump
    organize:
      EvoPop: share/themes/EvoPop
      EvoPop-Azure: share/themes/EvoPop-Azure
    stage:
      - share/themes/*/gtk-3*

  # Arc: common third party theme
  arc-theme:
    source: https://github.com/horst3180/arc-theme.git
    source-type: git
    plugin: autotools
    configflags:
      - --disable-cinnamon
      - --disable-gnome-shell
      - --disable-gtk2
      - --disable-metacity
      - --disable-unity
      - --disable-xfwm
