name: gtk-common-themes
version: git
version-script: |
  echo $(git describe --tags)
architectures:
  - all
summary: All the (common) themes
description: |
  A snap that exports the GTK and icon themes used on various Linux distros.

grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Adwaita
        - $SNAP/share/gtk2/Adwaita-dark
        - $SNAP/share/gtk2/HighContrast
        - $SNAP/share/gtk2/Ambiance
        - $SNAP/share/gtk2/Radiance
        - $SNAP/share/gtk2/Arc
        - $SNAP/share/gtk2/Arc-Dark
        - $SNAP/share/gtk2/Arc-Darker
        - $SNAP/share/gtk2/Communitheme
        - $SNAP/share/gtk2/Yaru
        - $SNAP/share/gtk2/elementary
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Adwaita
        - $SNAP/share/themes/Adwaita-dark
        - $SNAP/share/themes/HighContrast
        - $SNAP/share/themes/Ambiance
        - $SNAP/share/themes/Radiance
        - $SNAP/share/themes/Arc
        - $SNAP/share/themes/Arc-Dark
        - $SNAP/share/themes/Arc-Darker
        - $SNAP/share/themes/Communitheme
        - $SNAP/share/themes/Yaru
        - $SNAP/share/themes/elementary
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Adwaita
        - $SNAP/share/icons/hicolor
        - $SNAP/share/icons/HighContrast
        - $SNAP/share/icons/Humanity
        - $SNAP/share/icons/Humanity-Dark
        - $SNAP/share/icons/ubuntu-mono-dark
        - $SNAP/share/icons/ubuntu-mono-light
        - $SNAP/share/icons/DMZ-Black
        - $SNAP/share/icons/DMZ-White
        - $SNAP/share/icons/communitheme
        - $SNAP/share/icons/Suru
        - $SNAP/share/icons/Yaru
        - $SNAP/share/icons/elementary
  sound-themes:
    interface: content
    source:
      read:
        - $SNAP/share/sounds/communitheme
        - $SNAP/share/sounds/Yaru

parts:
  # The base icon theme
  hicolor-icon-theme:
    after: [utils]
    plugin: autotools
    source: git://anongit.freedesktop.org/xdg/default-icon-theme
    source-type: git
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    build-packages:
      - gnome-common

  # GNOME's default icon theme, also used by Fedora
  adwaita-icon-theme:
    after: [utils]
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/adwaita-icon-theme.git
    source-type: git
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - -share/pkgconfig

  # GNOME's default GTK theme, and Accessibility GTK/icon themes
  gnome-themes-extra:
    after: [utils]
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/gnome-themes-extra.git
    source-type: git
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/icons
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

    build-packages:
      - libgtk2.0-dev
      - libgtk-3-dev
      - librsvg2-dev
      - libgdk-pixbuf2.0-dev
      - libglib2.0-dev
      - gnome-common

  # Ubuntu's default GTK and icon themes
  ubuntu-themes:
    after: [utils]
    plugin: nil
    stage-packages:
      - light-themes
      - humanity-icon-theme
      - ubuntu-mono
      - dmz-cursor-theme
    override-build: |
      snapcraftctl build
      mv $SNAPCRAFT_PART_INSTALL/usr/share $SNAPCRAFT_PART_INSTALL/share
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/icons/Humanity
      - share/icons/Humanity-Dark
      - share/icons/ubuntu-mono-dark
      - share/icons/ubuntu-mono-light
      - share/icons/DMZ-Black
      - share/icons/DMZ-White
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

  # Elementary gtk theme
  elementary-gtk-theme:
    after: [utils, meson]
    plugin: meson
    source: https://github.com/elementary/stylesheet.git
    source-type: git
    meson-parameters: [--prefix=/]
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*
    build-packages:
      - libgtk-3-dev
      - libglib2.0-dev
      - gnome-common

  # Elementary icon theme
  elementary-icon-theme:
    after: [utils, meson]
    plugin: meson
    source: https://github.com/elementary/icons.git
    source-type: git
    # Set scale_factors to 1, it does some funky linking
    meson-parameters: [--prefix=/, -Dscale_factors=1, -Dvolume_icons=false]
    override-build: |
      # Don't include cursors, it does some funky linking
      sed -i.bak -e "s|subdir('cursors')||g" meson.build
      snapcraftctl build
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/elementary

  # Arc: common third party theme
  arc-theme:
    after: [utils]
    plugin: autotools
    source: https://github.com/NicoHood/arc-theme.git
    source-type: git
    configflags:
      - --disable-cinnamon
      - --disable-gnome-shell
      - --disable-metacity
      - --disable-unity
      - --disable-xfwm
      - --disable-plank
      - --disable-openbox
    build-packages:
      - libgtk-3-dev
      - libglib2.0-dev
      - inkscape
      - optipng
    override-build: |
      rm -f autogen.sh
      snapcraftctl build
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

  # Communitheme: we want the communitheme and this one to be in sync for bug reports
  # as it's a fast evolving WIP theme.
  # Download from select channel the corresponding snap (can be from a branch channel)
  # and copy its relevant content to this snap
  # It's currently only available on amd64 as built by Travis.
  communitheme:
    after: [utils]
    plugin: nil
    build-packages: [snapd]
    # note: build-snaps causes a segfault in docker
    override-pull: |
      set -eu
      snap download communitheme --edge
      unsquashfs communitheme*.snap
    override-build: |
      cp -a squashfs-root/share $SNAPCRAFT_PART_INSTALL/
      rm -rf $SNAPCRAFT_PART_INSTALL/share/gnome-shell/
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/icons
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

  # Yaru, the new official Ubuntu theme in 18.10 (formerly known by its code name Communitheme)
  yaru:
    after: [ utils, meson, sassc ]
    source: https://github.com/ubuntu/yaru.git
    plugin: meson
    meson-parameters: [ --prefix=/ ]
    override-build: |
      snapcraftctl build
      # remove unused artefacts in the snap (sessions and schemas)
      rm -rf $SNAPCRAFT_PART_INSTALL/share/*sessions $SNAPCRAFT_PART_INSTALL/share/glib-2.0
      # don't support dark variant until it's ready
      rm -r $SNAPCRAFT_PART_INSTALL/share/themes/*-dark
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
      $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/icons
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]

  meson:
    source: https://github.com/mesonbuild/meson/releases/download/0.48.0/meson-0.48.0.tar.gz
    plugin: python
    prime:
      - -*
  sassc:
    after: [ libsass ]
    source: https://github.com/sass/sassc.git
    source-tag: 3.5.0
    plugin: autotools
    prime:
      - -*
  libsass:
    source: https://github.com/sass/libsass.git
    source-tag: 3.5.0
    plugin: autotools
    prime:
      - -*
